# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WatchOsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'

end

target 'WatchOsTest WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatchOsTest WatchKit App

end

target 'WatchOsTest WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatchOsTest WatchKit Extension

end
